config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :blogs, only: [:index, :show, :destroy] do
      resources :blog_comments, only: [:destroy]
    end
    resources :orders, only: [:show, :index, :update]
    resources :reviews, only: [:index, :destroy]
    resources :blog_comments, only: [:index, :destroy]
  end
  
  scope module: :public do
    root to: "homes#top"
    get 'customers/unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw', as: 'withdraw'
    get 'customers/my_page/:id' => 'customers#show', as: 'my_page'
    get 'customers/edit' => 'customers#edit', as: 'edit'
    patch 'customers' => 'customers#update', as: 'update'
    get 'customers' => 'customers#index', as: 'index'
    get 'customers/profile_edit' => 'customers#profile_edit', as: 'profile_edit'
    patch 'customers/profile_update' => 'customers#profile_update', as: 'profile_update'
    get 'customers/favourite_blog' => 'customers#favourite_blog', as: 'favourite_blog'
    get 'customers/favourite_item' => 'customers#favourite_item', as: 'favourite_item'
    get 'customers/favourite_shop' => 'customers#favourite_shop', as: 'favourite_shop'
    get 'customers/customer_blog/:id' => 'customers#customer_blog', as: 'customer_blog'
    resources :shops, only: [:new, :create, :index, :show, :edit, :update] do
      resource :favourite_shops, only: [:create, :destroy]
    end
    resources :shop_orders, only: [:index, :show, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update] do
      resource :favourite_items, only: [:create, :destroy]
      collection do
        get "get_category_children", defaults: { format: "json" }
        get "menu_search"
      end
      member do
        get "item_search"
      end
      resources :reviews, only: [:create]
      get 'item_blog/:id' => 'items#item_blog', as: 'item_blog'
    end
    resources :blogs do
      resources :blog_comments, only: [:create, :destroy]
      resource :favourite_blogs, only: [:create, :destroy]
    end
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :carts, only: [:index, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
      resources :cart_items, only: [:destroy]
    end
    resources :orders, only: [:new, :create, :index, :show, :update]
    resources :relationships, only: [:create, :destroy]
    get 'customers/followers' => 'customers#followers', as: 'followers'
    get 'customers/followings' => 'customers#followings', as: 'followings'
    resources :notices, only: [:index]
    resources :checks, only: [:index]
    resources :shop_checks, only: [:index]
  end

  get '/item_search' => 'searches#item_search', as: 'item_search'
  get '/shop_search' => 'searches#shop_search', as: 'shop_search'
  get '/customer_search' => 'searches#customer_search', as: 'customer_search'
  get '/blog_search' => 'searches#blog_search', as: 'blog_search'

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#new_guest'
  end
  
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#new_guest'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  
  skip_before_action :authenticate_customer!, only: [:destroy]
  before_action :authenticate_admin!, only: [:index, :destroy]

  def index
    @reviews = Review.all.order(created_at: :desc)
  end

  def destroy
    Review.find(params[:id]).destroy
    redirect_to request.referer
  end
  
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-12">
      <div class="row d-flex justify-content-center my-3">
        <h4>レビュ一覧</h4>
      </div>
      <div class="row d-flex justify-content-center my-3">
        <div class="table-responsive">
          <table class="table table-bordered border-dark" style="width: 1140px;">
            <thead class="table-bordered bg-light">
              <tr>
                <th>作品名</th>
                <th>ショップ</th>
                <th>レビューしたユーザー</th>
                <th>レビューコメント</th>
                <th></th>
              </tr>
            </thead>
            <% @reviews.each do |review| %>
            <tbody>
              <tr>
                <td>
                  <%= link_to item_path(review.item.id), class: 'text-dark' do %>
                    <%= review.item.name %>
                  <% end %>
                </td>
                <td>
                  <%= link_to shop_path(review.item.shop.id), class: 'text-dark' do %>
                    <%= review.item.shop.name %>
                  <% end %>
                </td>
                <td>
                  <%= link_to admin_customer_path(review.customer.id), class: 'text-dark' do %>
                    <%= review.customer.user_name %>
                  <% end %>
                </td>
                <td><%= review.review_comment %></td>
                <td><%= link_to "削除", admin_review_path(review.id), method: :delete, "data-confirm" => "本当に消しますか？", class: 'text-dark' %></td>
              </tr>
            </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>