config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :blogs, only: [:index, :show, :destroy] do
      resources :blog_comments, only: [:destroy]
    end
    resources :orders, only: [:show, :index, :update]
    resources :reviews, only: [:index, :destroy]
    resources :blog_comments, only: [:index, :destroy]
  end
  
  scope module: :public do
    root to: "homes#top"
    get 'customers/unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw', as: 'withdraw'
    get 'customers/my_page/:id' => 'customers#show', as: 'my_page'
    get 'customers/edit' => 'customers#edit', as: 'edit'
    patch 'customers' => 'customers#update', as: 'update'
    get 'customers' => 'customers#index', as: 'index'
    get 'customers/profile_edit' => 'customers#profile_edit', as: 'profile_edit'
    patch 'customers/profile_update' => 'customers#profile_update', as: 'profile_update'
    get 'customers/favourite_blog' => 'customers#favourite_blog', as: 'favourite_blog'
    get 'customers/favourite_item' => 'customers#favourite_item', as: 'favourite_item'
    get 'customers/favourite_shop' => 'customers#favourite_shop', as: 'favourite_shop'
    get 'customers/customer_blog/:id' => 'customers#customer_blog', as: 'customer_blog'
    resources :shops, only: [:new, :create, :index, :show, :edit, :update] do
      resource :favourite_shops, only: [:create, :destroy]
    end
    resources :shop_orders, only: [:index, :show, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update] do
      resource :favourite_items, only: [:create, :destroy]
      collection do
        get "get_category_children", defaults: { format: "json" }
        get "menu_search"
      end
      member do
        get "item_search"
      end
      resources :reviews, only: [:create]
      get 'item_blog/:id' => 'items#item_blog', as: 'item_blog'
    end
    resources :blogs do
      resources :blog_comments, only: [:create, :destroy]
      resource :favourite_blogs, only: [:create, :destroy]
    end
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :carts, only: [:index, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
      resources :cart_items, only: [:destroy]
    end
    resources :orders, only: [:new, :create, :index, :show, :update]
    resources :relationships, only: [:create, :destroy]
    get 'customers/followers' => 'customers#followers', as: 'followers'
    get 'customers/followings' => 'customers#followings', as: 'followings'
    resources :notices, only: [:index]
    resources :checks, only: [:index]
    resources :shop_checks, only: [:index]
  end

  get '/item_search' => 'searches#item_search', as: 'item_search'
  get '/shop_search' => 'searches#shop_search', as: 'shop_search'
  get '/customer_search' => 'searches#customer_search', as: 'customer_search'
  get '/blog_search' => 'searches#blog_search', as: 'blog_search'

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#new_guest'
  end
  
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#new_guest'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  include ItemSearch
  before_action :set_parents
  
  def item_search
    @items = Item.search(params[:search])
    @Category = Category.where(ancestry: nil)
  end
  
  def shop_search
    @shops = Shop.search(params[:search])
  end
  
  def customer_search
    @customers = Customer.search(params[:search])
  end
  
  def blog_search
    @blogs = Blog.search(params[:search])
  end
  
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_blog_search.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h4 class="my-3"><i class="fas fa-gem"></i> ブログ一覧</h4>
    </div>
    <div class="col-12 text-right">
      <%= form_tag blog_search_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "ブログ検索" %>
        <%= button_tag :type => "submit", :title => nil do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>
  

app/views/searches/_customer_search.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h4 class="my-3"><i class="fas fa-gem"></i> ユーザー一覧</h4>
    </div>
    <div class="col-12 text-right">
      <%= form_tag customer_search_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "ユーザー検索" %>
        <%= button_tag :type => "submit", :user_name => nil do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>

app/views/searches/_item_search.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h4 class="my-3"><i class="fas fa-gem"></i> 作品一覧</h4>
    </div>
    <div class="col-12 text-right">
      <%= form_tag item_search_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "作品検索" %>
        <%= button_tag :type => "submit", :name => nil do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>

app/views/searches/_shop_search.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h4 class="my-3"><i class="fas fa-gem"></i> ショップ一覧</h4>
    </div>
    <div class="col-12 text-right">
      <%= form_tag shop_search_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "ショップ検索" %>
        <%= button_tag :type => "submit", :name => nil do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>
  

app/views/searches/blog_search.html.erb
<%= render 'blog_search', blog: @blog %>
    <% if @blogs.present? %>
    <div class="col-12 card-list-container">
      <div class="row d-flex justify-content-start">
      <%= render 'public/blogs/blog_list', blogs: @blogs %>
    <% else %>
    <div class="col-12 text-center m-3">
      <p>ブログの検索結果はありませんでした。</p>
      <p>キーワードを変更してもう一度検索してください。</p>
    </div>
    <% end %>
  </div>
</div>

app/views/searches/customer_search.html.erb
<%= render 'customer_search', customer: @customer %>
    <% if @customers.present? %>
    <div class="col-12 card-list-container">
      <div class="row d-flex justify-content-start">
      <%= render 'public/customers/customer_list', customers: @customers %>
    <% else %>
    <div class="col-12 text-center m-3">
      <p>ユーザーの検索結果はありませんでした。</p>
      <p>キーワードを変更してもう一度検索してください。</p>
    </div>
    <% end %>
  </div>
</div>

app/views/searches/item_search.html.erb
<%= render 'item_search', item: @item %>
    <div class="col-lg-12 col-sm-12 ">
      <%= render partial: 'public/items/category_item', items: @items %>
    </div>
    <% if @items.present? %>
    <div class="col-12 card-list-container">
      <div class="row d-flex justify-content-start">
      <%= render 'public/items/item_list', items: @items %>
    <% else %>
    <div class="col-12 text-center m-3">
      <p>作品の検索結果はありませんでした。</p>
      <p>キーワードを変更してもう一度検索してください。</p>
    </div>
    <% end %>
  </div>
</div>

app/views/searches/shop_search.html.erb
<%= render 'shop_search', shop: @shop %>
    <% if @shops.present? %>
    <div class="col-12 card-list-container">
      <div class="row d-flex justify-content-start">
      <%= render 'public/shops/shop_list', shops: @shops %>
    <% else %>
    <div class="col-12 text-center m-3">
      <p>ショップの検索結果はありませんでした。</p>
      <p>キーワードを変更してもう一度検索してください。</p>
    </div>
    <% end %>
  </div>
</div>


  