config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :blogs, only: [:index, :show, :destroy] do
      resources :blog_comments, only: [:destroy]
    end
    resources :orders, only: [:show, :index, :update]
    resources :reviews, only: [:index, :destroy]
    resources :blog_comments, only: [:index, :destroy]
  end
  
  scope module: :public do
    root to: "homes#top"
    get 'customers/unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw', as: 'withdraw'
    get 'customers/my_page/:id' => 'customers#show', as: 'my_page'
    get 'customers/edit' => 'customers#edit', as: 'edit'
    patch 'customers' => 'customers#update', as: 'update'
    get 'customers' => 'customers#index', as: 'index'
    get 'customers/profile_edit' => 'customers#profile_edit', as: 'profile_edit'
    patch 'customers/profile_update' => 'customers#profile_update', as: 'profile_update'
    get 'customers/favourite_blog' => 'customers#favourite_blog', as: 'favourite_blog'
    get 'customers/favourite_item' => 'customers#favourite_item', as: 'favourite_item'
    get 'customers/favourite_shop' => 'customers#favourite_shop', as: 'favourite_shop'
    get 'customers/customer_blog/:id' => 'customers#customer_blog', as: 'customer_blog'
    resources :shops, only: [:new, :create, :index, :show, :edit, :update] do
      resource :favourite_shops, only: [:create, :destroy]
    end
    resources :shop_orders, only: [:index, :show, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update] do
      resource :favourite_items, only: [:create, :destroy]
      collection do
        get "get_category_children", defaults: { format: "json" }
        get "menu_search"
      end
      member do
        get "item_search"
      end
      resources :reviews, only: [:create]
      get 'item_blog/:id' => 'items#item_blog', as: 'item_blog'
    end
    resources :blogs do
      resources :blog_comments, only: [:create, :destroy]
      resource :favourite_blogs, only: [:create, :destroy]
    end
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :carts, only: [:index, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
      resources :cart_items, only: [:destroy]
    end
    resources :orders, only: [:new, :create, :index, :show, :update]
    resources :relationships, only: [:create, :destroy]
    get 'customers/followers' => 'customers#followers', as: 'followers'
    get 'customers/followings' => 'customers#followings', as: 'followings'
    resources :notices, only: [:index]
    resources :checks, only: [:index]
    resources :shop_checks, only: [:index]
  end

  get '/item_search' => 'searches#item_search', as: 'item_search'
  get '/shop_search' => 'searches#shop_search', as: 'shop_search'
  get '/customer_search' => 'searches#customer_search', as: 'customer_search'
  get '/blog_search' => 'searches#blog_search', as: 'blog_search'

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#new_guest'
  end
  
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#new_guest'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true

default_scope -> { order(created_at: :desc) }
  belongs_to :customer
  belongs_to :item, optional: true
  has_many :blog_comments, dependent: :destroy
  has_many :favourite_blogs, dependent: :destroy
  has_many :notices, dependent: :destroy

  has_many_attached :blog_images
  
  def get_blog_images
    unless blog_images.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      blog_images.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    blog_images
  end
  
  def was_favourite_blog_by?(customer)
    favourite_blogs.exists?(customer_id: customer.id)
  end
  
  def create_notice_favourite_blog!(current_customer)
    temp = Notice.where(["visitor_id = ? and visited_id = ? and blog_id = ? and action = ? ", current_customer.id, customer_id, id, 'favourite_blog'])
    if temp.blank?
      notice = current_customer.active_notices.new(
        blog_id: id,
        visited_id: customer_id,
        action: 'favourite_blog'
      )
      if notice.visitor_id == notice.visited_id
        notice.checked = true
      end
      notice.save if notice.valid?
    end
  end
  
  def create_notice_blog_comment!(current_customer, blog_comment_id)
    temp_ids = BlogComment.select(:customer_id).where(blog_id: id).where.not(customer_id: current_customer.id).distinct
    temp_ids.each do |temp_id|
      save_notice_blog_comment!(current_customer, blog_comment_id, temp_id['customer_id'])
    end
    save_notice_blog_comment!(current_customer, blog_comment_id, customer_id) if temp_ids.blank?
  end

  def save_notice_blog_comment!(current_customer, blog_comment_id, visited_id)
    notice = current_customer.active_notices.new(
      blog_id: id,
      blog_comment_id: blog_comment_id,
      visited_id: visited_id,
      action: 'blog_comment'
    )
    if notice.visitor_id == notice.visited_id
      notice.checked = true
    end
    notice.save if notice.valid?
  end
  
  def self.search(search)
    if search
      Blog.where(["title LIKE?", "%#{search}%"])
    end
  end
  
  def self.create_blog_ranks
    Blog.find(FavouriteBlog.group(:blog_id).order('count(blog_id) desc').limit(4).pluck(:blog_id))
  end
  
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController

  before_action :authenticate_admin!, only: [:index, :show]
  
  def index
    @blogs = params[:item_id].present? ? Blog.where(item_id: nil) : Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
    @item = @blog.item
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to admin_blogs_path
  end
  
  def blog_params
    params.require(:blog).permit(:title, :body, :customer_id, :item_id, blog_images: [])
  end

end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/views/admin/blogs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h4 class="my-3"><i class="fas fa-gem"></i> ブログ一覧</h4>
    </div>
    
    <div class="offset-lg-10 offset-sm-8"></div>
    <div class="col-lg-2 col-sm-4 mt-3 text-right">
      <%= link_to admin_blogs_path, class: 'text-dark' do %>
        すべて
      <% end %>
      |
      <%= link_to admin_blogs_path(item_id: "nil"), class: 'text-dark' do %>
        オリジナル
      <% end %>
    </div>
    <div class="col-12 card-list-container">
      <div class="row d-flex justify-content-start">
      <% @blogs.each do |blog| %>
        <div class="col-lg-3 col-sm-6">
          <div class="card mx-auto my-3 shadow">
            <%= link_to admin_blog_path(blog) do %>
              <%= image_tag blog.get_blog_images.first.variant(gravity: :center, resize: "230x150^", crop: "230x150+0+0").processed, class: "card-img-top" %>
            <% end %>
            <%= render 'public/favourite_blogs/favourite_blog', blog: blog %>
            <div class="card-body">
              <div class="row">
                <div class="col-3 text-center">
                  <%= link_to admin_customer_path(blog.customer) do %>
                    <%= image_tag blog.customer.get_image.variant(gravity: :center, resize: "50x50^", crop: "50x50+0+0").processed, class: "rounded-circle" %>
                  <% end %>
                </div>
                <div class="col-8 text-center">
                  <%= link_to admin_blog_path(blog), class: "text-dark" do %>
                  <p class="card-title">
                    <%= blog.title %>
                  </p>
                  <% end %>
                  <p class="card-text">
                    <%= link_to admin_customer_path(blog.customer), class: "text-dark" do %>
                      <%= blog.customer.user_name %>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/blogs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 d-flex justify-content-center my-3">
      <h4 class="font-weight-bold mr-3 mt-1"><%= @blog.title %></h4>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-8 col-sm-12">
      <div class="row">
        <div class="col-12 d-flex justify-content-center">
          <div class="swiper">
            <div class="swiper-wrapper">
              <% @blog.get_blog_images.each do |blog_image| %>
                <div class="swiper-slide">
                  <%= image_tag blog_image, size: "500x300" %>
                </div>
              <% end %>
            </div>
            <div class="swiper-pagination"></div>
            <div class="swiper-button-prev text-warning"></div>
            <div class="swiper-button-next text-warning"></div>
          </div>
          <script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
          <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
          <%= javascript_pack_tag "swiper/swiper.js" %>
        </div>
      </div>
      <div class="row my-2">
        <div class="col-12">
          <p class="py-2 text-center"><%= @blog.body %></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="row">
        <div class="col-lg-8">
          <p class="mb-3"><%= @blog.created_at.to_s(:ymd) %></p>
        </div>
        <div class="col-lg-4">
          <p class="count ml-2 heart"><i class="fas fa-heart"></i> <%= @blog.favourite_blogs.count %></p>
        </div>
      </div>
      <p class="text-secondary">投稿者: </p>
      <%= link_to admin_customer_path(@blog.customer), class: 'text-dark' do %>
        <%= image_tag @blog.customer.get_image.variant(gravity: :center, resize: "50x50^", crop: "50x50+0+0").processed, class: "rounded-circle mr-2" %>
        <%= @blog.customer.user_name %>
      <% end %>
      <% unless @blog.item_id == nil %>
      <p class="text-secondary mt-3">作品: </p>
      <div class="row">
        <div class="col-lg-3 mr-2">
          <%= link_to item_path(@blog.item) do %>
            <%= image_tag @blog.item.get_item_images.first.variant(gravity: :center, resize: "50x50^", crop: "50x50+0+0").processed, class: "rounded-circle" %>
          <% end %>
        </div>
        <div class="col-lg-8">
          <%= link_to item_path(@blog.item), class: 'text-dark' do %>
            <%= @blog.item.name %>
          <% end %>
          <br>
          ¥<%= @blog.item.price.to_s(:delimited) %>円
        </div>
      </div>
      <p class="text-secondary mt-3">ショップ: </p>
      <div class="row">
        <div class="col-12 d-flex justify-content-start">
          <%= link_to shop_path(@item.shop) do %>
            <%= image_tag @item.shop.get_shop_icon_image.variant(gravity: :center, resize: "50x50^", crop: "50x50+0+0").processed, class: "mr-2 rounded-circle" %>
          <% end %>
          <%= link_to shop_path(@item.shop), class: 'text-dark' do %>
            <p class="pt-3"><%= @item.shop.name %></p>
          <% end %>
        </div>
      </div>
      <% end %>
      <div class="row">
        <div class="col-12 mt-3">
          <h5 class="pb-3 text-center">コメント</h5>
          <div class="d-flex justify-content-start">
            <p class="mr-3">コメント件数: </p>
            <%= @blog.blog_comments.count %>
          </div>
          <hr>
        </div>
      </div>
      <% @blog.blog_comments.each do |blog_comment| %>
      <div class="row">
        <div class="col-12 d-flex justify-content-start">
        <%= link_to admin_customer_path(blog_comment.customer), class: 'text-dark' do%>
          <%= image_tag blog_comment.customer.get_image.variant(gravity: :center, resize: "50x50^", crop: "50x50+0+0").processed, class: "mr-2 rounded-circle" %>
          <%= blog_comment.customer.user_name %>
        <% end %>
        </div>
      </div>
      <p class="py-1"><%= blog_comment.comment %></p>
      <div class="row">
        <div class="col-12 d-flex justify-content-start">
          <%= link_to "削除", admin_blog_blog_comment_path(blog_comment.blog, blog_comment), method: :delete, class: 'text-dark' %>
          <p class="ml-auto"><%= l blog_comment.created_at, format: :long %></p>
        </div>
      </div>
      <hr>
      <% end %>
    </div>
  </div>
</div>