config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :blogs, only: [:index, :show, :destroy] do
      resources :blog_comments, only: [:destroy]
    end
    resources :orders, only: [:show, :index, :update]
    resources :reviews, only: [:index, :destroy]
    resources :blog_comments, only: [:index, :destroy]
  end
  
  scope module: :public do
    root to: "homes#top"
    get 'customers/unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw', as: 'withdraw'
    get 'customers/my_page/:id' => 'customers#show', as: 'my_page'
    get 'customers/edit' => 'customers#edit', as: 'edit'
    patch 'customers' => 'customers#update', as: 'update'
    get 'customers' => 'customers#index', as: 'index'
    get 'customers/profile_edit' => 'customers#profile_edit', as: 'profile_edit'
    patch 'customers/profile_update' => 'customers#profile_update', as: 'profile_update'
    get 'customers/favourite_blog' => 'customers#favourite_blog', as: 'favourite_blog'
    get 'customers/favourite_item' => 'customers#favourite_item', as: 'favourite_item'
    get 'customers/favourite_shop' => 'customers#favourite_shop', as: 'favourite_shop'
    get 'customers/customer_blog/:id' => 'customers#customer_blog', as: 'customer_blog'
    resources :shops, only: [:new, :create, :index, :show, :edit, :update] do
      resource :favourite_shops, only: [:create, :destroy]
    end
    resources :shop_orders, only: [:index, :show, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update] do
      resource :favourite_items, only: [:create, :destroy]
      collection do
        get "get_category_children", defaults: { format: "json" }
        get "menu_search"
      end
      member do
        get "item_search"
      end
      resources :reviews, only: [:create]
      get 'item_blog/:id' => 'items#item_blog', as: 'item_blog'
    end
    resources :blogs do
      resources :blog_comments, only: [:create, :destroy]
      resource :favourite_blogs, only: [:create, :destroy]
    end
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :carts, only: [:index, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
      resources :cart_items, only: [:destroy]
    end
    resources :orders, only: [:new, :create, :index, :show, :update]
    resources :relationships, only: [:create, :destroy]
    get 'customers/followers' => 'customers#followers', as: 'followers'
    get 'customers/followings' => 'customers#followings', as: 'followings'
    resources :notices, only: [:index]
    resources :checks, only: [:index]
    resources :shop_checks, only: [:index]
  end

  get '/item_search' => 'searches#item_search', as: 'item_search'
  get '/shop_search' => 'searches#shop_search', as: 'shop_search'
  get '/customer_search' => 'searches#customer_search', as: 'customer_search'
  get '/blog_search' => 'searches#blog_search', as: 'blog_search'

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#new_guest'
  end
  
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#new_guest'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hands</title>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
    <script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <div class="col-12">
          <div class="row">
            <div class ="my-3 col-12 d-flex justify-content-center">
              <%= link_to 'ゲストログイン（閲覧用）', public_guest_sign_in_path, method: :post, class: 'mr-1' %>
              <%= link_to '管理者ゲストログイン（閲覧用）', admin_guest_sign_in_path, method: :post, class: 'ml-1' %>
            </div>
          </div>
          <div class="row d-flex justify-content-center">
            <div class ="col-lg-2 col-sm-4">
              <%= link_to root_path, class: 'head' do %>
                <h1 class="orange text-left">Hands</h1>
              <% end %>
            </div>
            <% if customer_signed_in? %>
            <div class ="col-lg-8 col-sm-8 mt-3">
              <div class="row">
                <div class="col-12 d-flex justify-content-end">
                  <%= link_to my_page_path(current_customer), class: 'head' do %>
                    <i class="fas fa-user-circle f-30 mr-2"></i>
                  <% end %>
                  <%= link_to carts_path, class: 'head' do %>
                    <i class="fas fa-shopping-cart f-30 mr-2"></i>
                  <% end %>
                  <%= link_to destroy_customer_session_path, method: :delete, class: 'head' do %>
                    <i class="fas fa-sign-out-alt f-30"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="row d-flex justify-content-center">
            <div class="col-lg-10">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="navbar-collapse collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <li class="mr-2">
                    <%= link_to "作品一覧", items_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li class="mr-2">
                    <%= link_to "ショップ一覧", shops_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li class="mr-2">
                    <%= link_to "ブログ一覧", blogs_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li>
                    <%= link_to "ユーザー一覧", index_path, class: 'btn btn-outline-secondary' %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
            <% elsif admin_signed_in? %>
            <div class ="col-lg-8 col-sm-8 mt-3">
              <div class="row">
                <div class="col-12 d-flex justify-content-end">
                  <%= link_to destroy_admin_session_path, method: :delete, class: 'head' do %>
                    <i class="fas fa-sign-out-alt f-30 mr-2"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="row d-flex justify-content-center">
            <div class="col-lg-10">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="navbar-collapse collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <li class="mr-2">
                    <%= link_to "作品一覧", items_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li class="mr-2">
                    <%= link_to "レビュ一覧", admin_reviews_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li class="mr-2">
                    <%= link_to "ショップ一覧", shops_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li class="mr-2">
                    <%= link_to "ブログ一覧", admin_blogs_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li class="mr-2">
                    <%= link_to "ブログコメント一覧", admin_blog_comments_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li class="mr-2">
                    <%= link_to "ユーザー一覧", admin_customers_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li>
                    <%= link_to "注文履歴一覧", admin_root_path, class: 'btn btn-outline-secondary' %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
            <% else %>
            <div class ="col-lg-8 col-sm-8 mt-3">
              <div class="row">
                <div class="col-12 d-flex justify-content-end">
                  <%= link_to new_customer_registration_path, class: 'head' do %>
                    <i class="fas fa-user-plus f-30 mr-2"></i>
                  <% end %>
                  <%= link_to new_customer_session_path, class: 'head' do %>
                    <i class="fas fa-sign-in-alt f-30 mr-2"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="row d-flex justify-content-center">
            <div class="col-lg-10">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="navbar-collapse collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <li class="mr-2">
                    <%= link_to "作品一覧", items_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li class="mr-2">
                    <%= link_to "ユーザー一覧", index_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li class="mr-2">
                    <%= link_to "ショップ一覧", shops_path, class: 'btn btn-outline-secondary' %>
                  </li>
                  <li>
                    <%= link_to "ブログ一覧", blogs_path, class: 'btn btn-outline-secondary' %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
            <% end %>
        </div>
      </div>
    </nav>
    <div class="my-2 text-center">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    </div>
    <main>
      <div class="my-2 text-center">
        <p id="notice"></p>
      </div>
      <%= yield %>
    </main>
    <footer>
      <p></p>
    </footer>
  </body>
</html>